replicaCount: 1
image:
  repository: hieubeo2369/api
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 5003
  nodePort: 30002
env:
  MONGO_URL: mongodb://hieu:123@db:27017/vtsStudent
ingress:
  enabled: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
